name: Deploy Next.js to VPS with PM2

on:
  push:
    branches: ["production"] # Hoặc "main" tùy vào nhánh bạn đang dùng thực tế
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "0.tcp.ap.ngrok.io"
          username: "khang"
          port: 10644
          key: ${{ secrets.DEPLOY_KEY }}
          source: ".next,public,package.json,package-lock.json,next.config.js,next.config.mjs"
          target: "/var/www/quanlycantin" 

      - name: Install & Restart PM2 on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "0.tcp.ap.ngrok.io"
          username: "khang"
          port: 10644
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/quanlycantin
            
            # Sử dụng đường dẫn tuyệt đối đã kiểm tra trên VPS của bạn
            /home/khang/.local/bin/npm install --production
            
            # Restart bằng đường dẫn tuyệt đối của PM2
            /home/khang/.local/bin/pm2 restart quanlycantin || /home/khang/.local/bin/pm2 start /home/khang/.local/bin/npm --name "quanlycantin" -- start
